<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="5TS206424426L7" name="com.nbcuni.test.nbcidx.member.undelete.brands.TC5084_MemberUndelete_ValidData" tests="1" failures="1" timestamp="26 Sep 2014 20:34:11 GMT" time="28.355" errors="0">
  <testcase name="memberUndelete_ValidData" time="28.355" classname="com.nbcuni.test.nbcidx.member.undelete.brands.TC5084_MemberUndelete_ValidData">
    <failure type="com.mongodb.MongoException$Network" message="Read operation to server localhost/127.0.0.1:27017 failed on database TURFIDXQ01">
      <![CDATA[com.mongodb.MongoException$Network: Read operation to server localhost/127.0.0.1:27017 failed on database TURFIDXQ01
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:253)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:216)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:288)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
	at com.mongodb.DBCursor._check(DBCursor.java:368)
	at com.mongodb.DBCursor._hasNext(DBCursor.java:459)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:484)
	at com.nbcuni.test.nbcidx.AppLib.getMongoDbResponse(AppLib.java:398)
	at com.nbcuni.test.nbcidx.MemberAPIs.memberUNDELETEResponseCode(MemberAPIs.java:679)
	at com.nbcuni.test.nbcidx.member.undelete.brands.TC5084_MemberUndelete_ValidData.memberUndelete_ValidData(TC5084_MemberUndelete_ValidData.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at org.bson.io.Bits.readFully(Bits.java:48)
	at org.bson.io.Bits.readFully(Bits.java:33)
	at org.bson.io.Bits.readFully(Bits.java:28)
	at com.mongodb.Response.<init>(Response.java:40)
	at com.mongodb.DBPort.go(DBPort.java:142)
	at com.mongodb.DBPort.call(DBPort.java:92)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:244)
	... 22 more
]]>
    </failure>
  </testcase> <!-- memberUndelete_ValidData -->
</testsuite> <!-- com.nbcuni.test.nbcidx.member.undelete.brands.TC5084_MemberUndelete_ValidData -->
