<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="5TS206424426L7" name="com.nbcuni.test.nbcidx.member.login.hmac.TC4026_MemberLogin_HMAC_Errors" tests="1" failures="0" timestamp="26 Sep 2014 20:34:11 GMT" time="0.734" errors="1">
  <testcase name="memberLogin_HMAC_errors" time="0.734" classname="com.nbcuni.test.nbcidx.member.login.hmac.TC4026_MemberLogin_HMAC_Errors">
    <error type="java.lang.AssertionError" message="Member.login Response code =404">
      <![CDATA[java.lang.AssertionError: Member.login Response code =404
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at com.nbcuni.test.nbcidx.member.login.hmac.TC4026_MemberLogin_HMAC_Errors.memberLogin_HMAC_errors(TC4026_MemberLogin_HMAC_Errors.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- memberLogin_HMAC_errors -->
</testsuite> <!-- com.nbcuni.test.nbcidx.member.login.hmac.TC4026_MemberLogin_HMAC_Errors -->
